"""use sqlite

Revision ID: 95ff5cb2bf5c
Revises: 
Create Date: 2021-02-10 22:51:36.592343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ff5cb2bf5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('relevant_experience', sa.Text(), nullable=True),
    sa.Column('education_level', sa.Text(), nullable=True),
    sa.Column('major_discipline', sa.Text(), nullable=True),
    sa.Column('company_type', sa.Text(), nullable=True),
    sa.Column('company_size', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
